name: json_hydrator
version: 0.0.1
description: Converts JSON to true dart objects, and back again.
author: Sean McCleary <sean.mccleary@gmail.com>
homepage: https://bitbucket.org/seanmccleary/json_hydrator
dependencies:
  logging: ">=0.9.2 <0.10.0"
  unittest: ">=0.11.0+3 <0.12.0"