name: json_hydrator
description: Convert dart objects to and from JSON
version: 1.0.0-alpha
author: Sean McCleary <sean.mccleary@gmail.com>
homepage: https://github.com/seanmccleary/json_hydrator

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '^0.12.0'
  source_gen: '^0.5.0'
  build_runner: '^0.1.0'
